### ISSUE TITLE
[Post PE-D] Valid duplicated tags not accepted as input

### ISSUE THREAD

**Issue by sarahchow03** [AY2425S1-CS2113-T10-3/tp#158]
Mentioned in #132 and #150 .

**Comment by xenthm** [comment]
`MangaTantou` is designed to look for its valid flags (i.e. ` -a `, ` -d `, ` -s `) and will stop at each flag and process the inputs between the valid flags as arguments for the preceding flag (i.e. `catalog -a Kubo Tite -a Bleach` will give just `Kubo Tite`). In other words, `MangaTantou` is <ins>**smart enough**</ins> to ignore duplicate flags where it is not expecting them and will only <ins>**take the first**</ins> valid input it encounters. Should the user require an input that contains a flag (i.e. `Kubo -a Tite` is the author's name), we recommend that the user encloses the offending part of the name with quotation marks (i.e. `Kubo "-a" Tite`). This is a tradeoff that `MangaTantou` takes for flexibility in argument inputs.

**Comment by xenthm** [comment]
# Limitation
Additionally, if you decide to manually edit the data file such that an entry contains a field that is impossible to add via normal commands (i.e. authorName `Kubo -a Tite` instead of `Kubo --a Tite`), you <ins>**will not be**</ins> able to access this entry in via normal commands in the future unless this change is corrected.
