### ISSUE TITLE
[Post PE-D] Data corruption handling

### ISSUE THREAD

**Issue by sarahchow03** [AY2425S1-CS2113-T10-3/tp#164]
Mentioned in #140 and #156.

**Comment by xenthm** [comment]
# Additional Issue
When using the following data file: 
```
[
  {
    "authorName": "test",
    "mangaList": []
  },
]
```
The additional comma at the end causes a `null` author to be added to `authorList`. This is not caught during deserialization. When the `view` command is inputted, the program crashes with the following message: `NullPointerException: Cannot invoke "author.Author.getAuthorName()" because "author" is null`.

**Comment by xenthm** [comment]
# Todo
- [x] Fix `NullPointerException`
- [ ] Perform validity checks on each field in the data file (duplicates, invalid values, etc.)
